version: '3.1'

services:

  humhub:
    image: levtecaccess/humhub:1.3.14
    container_name: humhub
    depends_on:
      - humhubdb
    links:
      - humhubdb:humhubdb
    ports:
      - "8010:80"
      - "8011:443"
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'humhubdb'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 0
      HUMHUB_DEBUG: 0
      HUMHUB_PROTO: 'http'
      HUMHUB_HOST: 'localhost'
    volumes:
      - "./data/config:/var/www/localhost/htdocs/protected/config"
      - "./data/uploads:/var/www/localhost/htdocs/protected/uploads"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  humhubdb:
    image: mariadb:latest
    container_name: humhubdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
