version: "2"

services:

  mattermost-db:
    image: levtecaccess/mattermost_db:latest
    container_name: mattermost-db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password_17728282y1gh2
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  mattermost-app:
    image: levtecaccess/mattermost_app:latest
    container_name: mattermost-app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password_17728282y1gh2
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      # - MM_CONFIG=/mattermost/config/config.json

  mattermost-web:
    image: levtecaccess/mattermost_web:latest
    container_name: mattermost-web
    read_only: true
    restart: unless-stopped
    ports:
      - "8065:80"
      - "8067:443"
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_HTTP_PORT=8065
      - MATTERMOST_HTTPS_PORT=8067
      # Uncomment for SSL
      - MATTERMOST_ENABLE_SSL=true
