version: "2"

services:

  roundcube:
    image: roundcube/roundcubemail:latest-apache
    container_name: roundcube
    restart: always
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 8040:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql # Database type to use
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as mysql container name
      - ROUNDCUBEMAIL_DB_NAME=roundcube # same as mysql MYSQL_DATABASE env name
      - ROUNDCUBEMAIL_DB_USER=roundcube # same as mysql MYSQL_USER env name
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcubedbpass # same as mysql MYSQL_PASSWORD env name
      - ROUNDCUBEMAIL_DEFAULT_HOST=imap.gmail.com # hostname of the default imap server to connect to
      - ROUNDCUBEMAIL_DEFAULT_PORT=143 # default imap server port number
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp.gmail.com # hostname of the default smtp server to send mails
      - ROUNDCUBEMAIL_SMTP_PORT=587 # default smtp server port number
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=50M # maximum upload size for email attachments
    volumes:
      - ./data/html:/var/www/html # Roundcube HTML data

  roundcubedb:
    image: mariadb:latest
    container_name: roundcubedb
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql # Roundcube SQL DB storage volume
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=roundcube
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcubedbpass
