version: '2'

services:

  freepbx-server:
    container_name: freepbx-server
    image: tiredofit/freepbx
    restart: always
    links:
      - freepbx-db
      - freepbx-db-backup
    ports:
      - 8070:80
      - 8071:443
      - 5060:5060
      - 5160:5160
      - 18000-18100:18000-18100/udp
      ## Flash Operator Panel
      - 4445:4445
    volumes:
      - ./data/certs:/certs
      - ./data/data:/data
      - ./data/logs:/var/log
      - ./data/www:/var/www/html
      ## Only Enable this option below if you set DB_EMBEDDED=TRUE
      #- ./db:/var/lib/mysql
      ## You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
      #- ./assets/custom:/assets/custom
    environment: 
      - VIRTUAL_HOST=hostname.example.com
      - VIRTUAL_NETWORK=freepbx-proxy
      - VIRTUAL_PROTO=http
      # - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=8070
      ## If you want to connect to the SSL Enabled Container, rename the below variable
      - VIRTUAL_PORT2=8071
      # - LETSENCRYPT_HOST=hostname.example.com
      # - LETSENCRYPT_EMAIL=email@example.com
      - ZABBIX_HOSTNAME=freepbx-server
      - RTP_START=18000
      - RTP_FINISH=18100
      ## Use for External MySQL Server
      - DB_EMBEDDED=FALSE
      ## These are only necessary if DB_EMBEDDED=FALSE
      - DB_HOST=freepbx-db
      - DB_PORT=3306
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
      #- TLS_CERT=cert.pem
      #- TLS_KEY=key.pem
    networks:
      - proxy-tier
    ## These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    privileged: true

  freepbx-db:
    container_name: freepbx-db
    image: tiredofit/mariadb
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
    networks:
      - proxy-tier

  freepbx-db-backup:
    container_name: freepbx-db-backup
    image: tiredofit/db-backup
    restart: always
    links:
      - freepbx-db
    volumes:
      - ./data/db-backup:/backup
    environment:
      - ZABBIX_HOSTNAME=freepbx-db-backup
      - DB_HOST=freepbx-db
      - DB_TYPE=mariadb
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: freepbx-proxy
