version: '3.3'

services:

  freepbx-server:
    image: flaviostutz/freepbx:14.1.1
    restart: always
    ports:
      - 8070:80
      - 8071:443
      - 5060:5060/udp
      - 5061:5061/udp
      - 5160:5160/udp
      - 5161:5161/udp
      - 10000-10250:10000-10250/udp
      - 4569:4569/udp
    volumes:
      - freepbx-backup:/backup
      - freepbx-logs:/var/log/asterisk
      - freepbx-recordings:/var/spool/asterisk/monitor
      - freepbx-www:/var/www/html
      - apache2-config:/etc/apache2

volumes:
  freepbx-backup:
  freepbx-logs:
  freepbx-recordings:
  freepbx-www:
  apache2-config:
