version: '3.3'

services:

  freepbx-server:
    container_name: freepbx-server
    build: .
    image: flaviostutz/freepbx:14.0
    network_mode: host
    restart: always
    ports:
      - 8070:80
      - 5060:5060
    volumes:
      - freepbx-backup:/backup
      - freepbx-recordings:/var/spool/asterisk/monitor

volumes:
  freepbx-backup:
  freepbx-recordings:
