version: "2"

services:

  # Mail server suitable for use with RoundCube: https://github.com/tomav/docker-mailserver
  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.name.com
    container_name: mail
    restart: always
    ports:
      # receiving email from other mailservers
      - "25:25"
      # SSL & TLS Client email submission (SMTP)
      - "465:465"
      - "587:587"
      # StarTLS & TLS/SSL IMAP client
      - "143:143"
      - "993:993"
      # POP3 & TLS/SSL POP3 client
      - "110:110"
      - "995:995"
      # Manage Sieve port
      - "4190:4190"
    environment:
      - DMS_DEBUG=0
      - ONE_DIR=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_MANAGESIEVE=1
      # If you need SSL connection, you can provide your own certificates
      #- SSL_TYPE=manual
      #- SSL_CERT_PATH=/etc/letsencrypt/fullchain.pem
      #- SSL_KEY_PATH=/etc/letsencrypt/privkey.pem
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    volumes:
      - ./data/data:/var/mail
      - ./data/state:/var/mail-state
      # For proper delivery, generate DKIM keys in /srv/mail/setup
      - ./data/setup:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
